/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example;
@org.apache.avro.specific.AvroGenerated
public enum Direction implements org.apache.avro.generic.GenericEnumSymbol<Direction> {
  NORTH, SOUTH, EAST, WEST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Direction\",\"namespace\":\"example\",\"symbols\":[\"NORTH\",\"SOUTH\",\"EAST\",\"WEST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
